export const departments = [
  "HR",
  "IT",
  "Finance",
  "Marketing",
  "Sales",
  "Operations",
];

export const roles = [
  "Manager",
  "Developer",
  "Analyst",
  "Designer",
  "Associate",
  "Director",
];

export const mockEmployees = [
  {
    id: 1,
    firstName: "Alice",
    lastName: "Smith",
    email: "alice@example.com",
    department: "HR",
    role: "Manager",
  },
  {
    id: 2,
    firstName: "Bob",
    lastName: "Johnson",
    email: "bob@example.com",
    department: "IT",
    role: "Developer",
  },
  {
    id: 3,
    firstName: "Charlie",
    lastName: "Lee",
    email: "charlie@example.com",
    department: "Finance",
    role: "Analyst",
  },
  {
    id: 4,
    firstName: "Diana",
    lastName: "Wilson",
    email: "diana@example.com",
    department: "Marketing",
    role: "Designer",
  },
  {
    id: 5,
    firstName: "Edward",
    lastName: "Brown",
    email: "edward@example.com",
    department: "Sales",
    role: "Associate",
  },
  {
    id: 6,
    firstName: "Fiona",
    lastName: "Davis",
    email: "fiona@example.com",
    department: "Operations",
    role: "Director",
  },
  {
    id: 7,
    firstName: "George",
    lastName: "Miller",
    email: "george@example.com",
    department: "IT",
    role: "Manager",
  },
  {
    id: 8,
    firstName: "Helen",
    lastName: "Garcia",
    email: "helen@example.com",
    department: "HR",
    role: "Associate",
  },
  {
    id: 9,
    firstName: "Ivan",
    lastName: "Rodriguez",
    email: "ivan@example.com",
    department: "Finance",
    role: "Manager",
  },
  {
    id: 10,
    firstName: "Julia",
    lastName: "Martinez",
    email: "julia@example.com",
    department: "Marketing",
    role: "Developer",
  },
];
